
[functions.create-paypal-order]
enabled = true
verify_jwt = true
import_map = "./functions/create-paypal-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-paypal-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-paypal-order/*.html" ]

[functions.gumroad-webhook-handler]
verify_jwt = false

[functions.get-ai-move]
verify_jwt = true

[functions.import-opening-book]
verify_jwt = true
